In [1]:
1.
    
#Sort the list and find the max and min age

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
ages.sort()
print("1. The sorted list of ages:", ages)
print("\tThe minimum age is:", min(ages))
print("\tThe maximum age is:", max(ages))

#Add the minimum age and the maximum age again to the list

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
ages.append(19)
ages.append(26)
print("2. The final list is:", ages)

#Find the median age

import statistics as st
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24, 19, 26]
median_age = st.median(ages)
print("3. The median age of the list is:", median_age)

#Find the average age

from statistics import mean
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24, 19, 26]

mean_age= mean(ages)
print("4. The average age of the list is:", mean_age)

#Find the range of the ages (maximum minus min)

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24, 19, 26]

maximum_age = maximum(ages)
minimum_age = minimum(ages)
range = maximum_age - minimum_age
print("5. The range of the ages is:", range)

1. The sorted list of ages: [19, 19, 20, 22, 24, 24, 24, 25, 25, 26]

NameError: name 'minimum' is not defined

In [ ]:
2.

#Create an empty dictionary called dog

dog = {}
print("1. Created an empty dictionary called dog", dog)

#Add name, color, breed, legs, age to the dog dictionary

dog = {
    "name": "Julie", "color" : "brown", "breed" : "german shepherd", "legs" : "4", "age" : "5"
}
print("2. Adding the elements to the dictionary", dog)

#Create a student dictionary and add first_name, last_name, gender, age, marital status, skills, country, city and address as keys for the dictionary

student = {'first_name':'ABC','last_name':'XYZ','gender':'M','age':'25','martial status':'Unmarried','skills':['Python','C'],'country':'USA','city':'Kansas city','address':'2538 W 126th ter'}
print("3. Created student dictionary:",student)

#Get the length of the student dictionary

print("4. length of dictionary:",len(student))

#Get the value of skills and check the data type, it should be a list

print("5. The value of skills is:", student.get('skills'))
print("\tThe data type of skills is:",type(student['skills']))

#Modify the skills values by adding one or two skills

student['skills'].append('java')
student['skills'].append('SQL')
print("6. The updated skills list is:", student)

#Get the dictionary keys as a list

print("7. The student dictionary keys as list:", student.keys())

#Get the dictionary values as a list

print("8. The student dictionary values as a list:", student.values())

In [ ]:
3.

#Create a tuple containing names of your sisters and your brothers (imaginary siblings are fine)

sisters = ("Amy","Candice","Jenny")
brothers = ("Will","Kate","Harry")
print("1. Siblings names are:", sisters, brothers)

#Join brothers and sisters tuples and assign it to siblings

siblings = sisters+brothers
print("2. Joining the tuples:", siblings)

#How many siblings do you have?

print("3. length of siblings:", len(siblings))

#Modify the siblings tuple and add the name of your father and mother and assign it to family_members

siblings = list(siblings)
siblings.append("John")
siblings.append("Mary")
family_members = tuple(Siblings)
print("4. Modified Family members tuple:", Family_members)

In [ ]:
4.

it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
age = [22, 19, 24, 25, 26, 24, 25, 24]

#Find the length of the set it_companies

print("1. Length of IT Companies:", len(it_companies))

#Add 'Twitter' to it_companies

it_companies.add('Twitter')
print("2. Updated set of it companies:", it_companies)

#Insert multiple IT companies at once to the set it_companies

mult_companies = ["AT&T", "Samsung", "Dell"]
it_companies.update(mult_companies)
print("3. After inserting multiple companies:", it_companies)

#Remove one of the companies from the set it_companies

it_companies.discard("AT&T")
print("4. Deleting one company from set:", it_companies)

#What is the difference between remove and discard

#Both remove() & discard() give same result, but the difference is when we use discard() to eliminate some value from 
#the set if it is present it will be deleted, if it is not then it will never raise any error. If we use remove() method to 
#delete a value from set, if the value is present then it will delete otherwise it will raise error.

#Join A and B

C = A.union(B)
print("6. After joining sets:", C)

#Find A intersection B

D = A.intersection(B)
print("7. After intersection the set is:", D)

#Is A subset of B

E = A.issubset(B)
print("8. Is A subset of B:", E)

#Are A and B disjoint sets

F = A.isdisjoint(B)
print("9. Are A and B disjoint sets:", F)

#Join A with B and B with A

X = A.union(B)
Y = B.union(A)
print("10. Joining A with B:", X)
print("\tJoining B with A:", Y)

#What is the symmetric difference between A and B

Z = A.symmetric_difference(B)
print("11. Symmetric difference between A and B:", Z)

#Delete the sets completely

#del A
#print("deleting set A:", A)
#del B
#print("deleting set B:", B)

#Convert the ages to a set and compare the length of the list and the set

K = set(age)
print("13. Conerting list to set:", K)

s = len(K)
print(s)
p = len(age)
print(p)

if p==s:
    print("Identical")
else:
    print("Different")

In [ ]:
5.

#The radius of a circle is 30 meters.

#Calculate the area of a circle and assign the value to a variable name of _area_of_circle_

import math
radius = 30
_area_of_circle_ = math.pi*radius*radius
print("1. The area of circle:",_area_of_circle_)

#Calculate the circumference of a circle and assign the value to a variable name of _circum_of_circle_

_circum_of_circle_ = 2*math.pi*radius
print("2. The circumference of circle:", _circum_of_circle_)

#Take radius as user input and calculate the area
radii = float(input("The radius of circle:")) 
area = math.pi*radii*radii
print("3. The radius of area:",area)

In [ ]:
6.

#“I am a teacher and I love to inspire and teach people”

#How many unique words have been used in the sentence? Use the split methods and set to get the unique word
string = "I am a teacher and I love to inspire and teach people"
new_words = string.split(" ")
n = 0
for word in new_words:
    word_count = new_words.count(word)
    if word_count == 1:
        n += 1
print("The number of unique words:", n)

In [ ]:
7.

#Use a tab escape sequence to get the following lines

print("Name\tAge\tCountry\tCity\nAsabench\t250\tFinland\tHelsinki")

In [ ]:
8.

#Use the string formatting method to display the following:

radius = 10
area = int(3.14 * radius ** 2)
print("The area of a circle with radius", radius,"is", area, "meters square.")

In [ ]:
9.

list= []
  
n = int(input("Enter n"))
  
for i in range(0, n):
    new_value = int(input())
    list1 = new_value*0.453592
      
    list.append(list1) 
      
print(list)

Enter n4
150
155
145
148
[68.0388, 70.30676, 65.77083999999999, 67.131616]

In [ ]:
lst = []
  

n = int(input("Enter number of Students : "))
  
for i in range(0, n):
    ele = int(input("Enter weights of students in Lb:"))
  
    lst.append(ele)
      
print(lst)

lst_kg=[i *0.45359237 for i in lst]

print("Students weight in Kg:"+str(lst_kg))

Enter number of Students : 4
Enter weights of students in Lb:150 155 145 148

ValueError: invalid literal for int() with base 10: '150 155 145 148'